services:
  app:
    build:
      context: .
      args:
        - DATABASE_URL=postgresql://postgres:postgres@db:5432/imposu?schema=public
    ports:
      - '3000:8080'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/imposu?schema=public
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_TRUST_HOST=true
    env_file:
      - .env.local
    volumes:
      - ./:/src
      - /src/node_modules
      - /src/.next

  db:
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=imposu
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
